POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Implc2plcyIsImlkIjoiNWMwYmJlYjQwMDY0M2I0MjE5YzE3NmM3IiwiaWF0IjoxNTQ0Mjc0MzQzfQ.zGzw_dHjZhIJCZXmsuyuZHLw8Tr6NpCClSVTSOpFK_U

{
    "title": "token jee",
    "author": "toknen",
    "url": "www.token.com",
    "likes": 6661
}